name: GashiBattleBus
version: '1.0'
main: com.github.gashiBattleBus.GashiBattleBus
api-version: '1.20'
authors: [ gashi ]
commands:
  battlebus:
    description: Start the battle bus.
    usage: /battlebus x1 y1 z1 x2 y2 z2 time